# 1.Cargar archivos

In [ ]:
import pandas as pd
import seaborn
import matplotlib.pyplot as plt
import numpy

In [ ]:
worldcups = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Fifa World Cup - EDA/data/WorldCups.csv')

In [ ]:
players_worldcups = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Fifa World Cup - EDA/data/WorldCupPlayers.csv')

In [ ]:
matches_worldcups = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Fifa World Cup - EDA/data/WorldCupMatches.csv')

# 2.Conocer y Transformar Dataframe

In [ ]:
worldcups.info()
#Se podria cambiar el a√±o a tipo date pero no nos genera valor entonces es mejor dejarlo en int
#El attendance si debemos cambiarlo a int
#Este df se relacioan con el de matches usando year

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Year            20 non-null     int64
 1   Country         20 non-null     object
 2   Winner          20 non-null     object
 3   Runners-Up      20 non-null     object
 4   Third           20 non-null     object
 5   Fourth          20 non-null     object
 6   GoalsScored     20 non-null     int64
 7   QualifiedTeams  20 non-null     int64
 8   MatchesPlayed   20 non-null     int64
 9   Attendance      20 non-null     int64
dtypes: int64(5), object(5)
memory usage: 1.7+ KB

In [ ]:
players_worldcups.info()
#Conocer la columna Event que tiene
#Analizar si existe alguna columna que pueda funcionar como primary key
#Mirar como tratar los valores nulos
#Ver vinculo con la tabla matches , con round o match id para hacer algun join

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37784 entries, 0 to 37783
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   RoundID        37784 non-null  int64
 1   MatchID        37784 non-null  int64
 2   Team Initials  37784 non-null  object
 3   Coach Name     37784 non-null  object
 4   Line-up        37784 non-null  object
 5   Shirt Number   37784 non-null  int64
 6   Player Name    37784 non-null  object
 7   Position       4143 non-null   object
 8   Event          9069 non-null   object
dtypes: int64(3), object(6)
memory usage: 2.6+ MB

In [ ]:
matches_worldcups.info()
#Cambiar Year a int
#Datetime pasarlo a tipo datetime
#Wind conditions entender que valores tiene
#Attendance pasarlo a int64
#half time home and away goals pasarlos a int
#Round ID y match ID pasarlos a int
#Mirar como tratar los valores nulos
#Analizar si existe alguna columna que pueda funcionar como primary key

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    object
 2   Stage                 852 non-null    object
 3   Stadium               852 non-null    object
 4   City                  852 non-null    object
 5   Home Team Name        852 non-null    object
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    object
 9   Win conditions        852 non-null    object
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    object
 14  Assistant 1           852 non-null    object
 15  Assistant 2           852 non-null    object
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    object
 19  Away Team Initials    852 non-null    object
dtypes: float64(8), object(12)
memory usage: 714.5+ KB

In [ ]:
matches_worldcups.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

## 2.1 Identificar valores nulos

In [ ]:
worldcups.isnull().sum() # Ningun valor nulo, correcto

Year              0
Country           0
Winner            0
Runners-Up        0
Third             0
Fourth            0
GoalsScored       0
QualifiedTeams    0
MatchesPlayed     0
Attendance        0
dtype: int64

In [ ]:
players_worldcups.isnull().sum() #Valores nulos en posici√≥n y evento

RoundID              0
MatchID              0
Team Initials        0
Coach Name           0
Line-up              0
Shirt Number         0
Player Name          0
Position         33641
Event            28715
dtype: int64

In [ ]:
matches_worldcups.isnull().sum() #Valores nulos en todas las columnas

Year                    3720
Datetime                3720
Stage                   3720
Stadium                 3720
City                    3720
Home Team Name          3720
Home Team Goals         3720
Away Team Goals         3720
Away Team Name          3720
Win conditions          3720
Attendance              3722
Half-time Home Goals    3720
Half-time Away Goals    3720
Referee                 3720
Assistant 1             3720
Assistant 2             3720
RoundID                 3720
MatchID                 3720
Home Team Initials      3720
Away Team Initials      3720
dtype: int64

## 2.2 DF World Cups - EDA
Informaci√≥n que podriamos extraer
- Top  paises mas ganadores de mundiales
- Top 10 mundiales con mas goles
- Top 5 mundiales con mas asistencias de publico
- Paises que han sido sede mas de una vez
- Total de goles anotados en todos los mundiales que estan registrados
- Total de asistencias
- Paises que fueron campeones siendo sede

In [ ]:
worldcups

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1045246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1563135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1603975
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1865753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1545791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2109723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2394031
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2516215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3587538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2785100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2705197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3359439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3178856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3386810

### 2.2.1 Convertir tipos de datos en las columnas

In [ ]:
def data_transform(valor):
  #Funci√≥n para reemplazar los . por ningun espacio para luego convertir a int64 toda la tabla
  nuevo_valor = valor.replace(".","")
  return nuevo_valor

In [ ]:
worldcups['Attendance'] = worldcups['Attendance'].apply(data_transform) #Aplicar funci√≥n de data_transform

In [ ]:
worldcups['Attendance'] = worldcups['Attendance'].astype('int64') #Pasar a int64 toda la tabla

### 2.2.2 Encontrar insigths

Top ganadores de copas del mundo

In [ ]:
result_winners = worldcups.get(['Country','Winner']).groupby('Winner',as_index=False).count().sort_values(by='Country',ascending=False)

In [ ]:
result_winners = result_winners.rename(columns={'Country': 'quantity'})

In [ ]:
result_winners.reset_index(drop=True)

       Winner  quantity
0      Brazil         5
1       Italy         4
2  Germany FR         3
3   Argentina         2
4     Uruguay         2
5     England         1
6      France         1
7     Germany         1
8       Spain         1

Top 10 mundiales con mas goles

In [ ]:
worldcups.sort_values(by='GoalsScored',ascending=False).head(10)

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3386810
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2785100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2705197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3359439
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2109723
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3178856
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3587538
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768607
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2394031
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819810

Top 5 asistencias en mundiales

In [ ]:
worldcups.sort_values(by='Attendance',ascending=False).head(5)

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3587538
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3386810
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3359439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3178856
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2785100

Paises que han sido sede mas de una vez

In [ ]:
sedes_mundiales = worldcups.get(['Country','Winner']).groupby('Country',as_index=False).count().sort_values(by='Winner',ascending=False).reset_index(drop=True)

In [ ]:
sedes_mundiales = sedes_mundiales.rename(columns={'Winner': 'quantity'})

In [ ]:
sedes_mundiales.query('quantity > 1')

   Country  quantity
0   Brazil         2
1   France         2
2  Germany         2
3    Italy         2
4   Mexico         2

- Total de goles anotados
- Total de asistencias
- Promedio de Gol x Partido

In [ ]:
metricas = worldcups[['GoalsScored','Attendance','MatchesPlayed']].sum().reset_index()

In [ ]:
metricas.columns = ['Metric','Total']

In [ ]:
avg_goal = round(metricas.loc[0][1] / metricas.loc[2][1], 2) #

In [ ]:
metricas.loc[len(metricas.index)] = ['Avg Goal x Match ',avg_goal]

In [ ]:
metricas

              Metric        Total
0        GoalsScored      2379.00
1         Attendance  37457647.00
2      MatchesPlayed       836.00
3  Avg Goal x Match          2.85

Campeones siendo sede

In [ ]:
worldcups[['Year','Country','Winner']].query('Country == Winner')

    Year    Country     Winner
0   1930    Uruguay    Uruguay
1   1934      Italy      Italy
7   1966    England    England
10  1978  Argentina  Argentina
15  1998     France     France

## 2.3 DF Players World Cups - EDA

In [ ]:
players_worldcups.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN

### 2.3.1 Conocer Valores unicos de  columna posici√≥n

In [ ]:
players_worldcups['Position'].unique()
#GK --> Arquero
#C --> Capitan
#GKC --> Arquero y Capitan

array(['GK', nan, 'C', 'GKC'], dtype=object)

In [ ]:
players_worldcups.loc[(players_worldcups['Position'].isin(['GKC']))].tail(100)

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
20655,337,3061,BUL,PENEV Dimitar (BUL),S,1,Borislav MIHAYLOV,GKC,NaN
20699,337,3060,ESP,CLEMENTE Javier (ESP),S,1,ZUBIZARRETA,GKC,NaN
20786,337,3063,USA,MILUTINOVIC Bora (YUG),S,1,Tony MEOLA,GKC,NaN
20874,337,3065,KOR,KIM Ho Kon (KOR),S,1,CHOI In Young,GKC,NaN
20963,337,3068,RUS,SADYRIN Pavel (RUS),S,16,Dmitri KHARIN,GKC,Y34'
...,...,...,...,...,...,...,...,...,...
36404,255951,300186462,FRA,DESCHAMPS Didier (FRA),S,1,LLORIS,GKC,NaN
36542,255953,300186485,FRA,DESCHAMPS Didier (FRA),S,1,LLORIS,GKC,NaN
37049,255951,300186487,CHI,SAMPAOLI Jorge (ARG),S,1,C. BRAVO,GKC,NaN
37232,255951,300186462,FRA,DESCHAMPS Didier (FRA),S,1,LLORIS,GKC,NaN
37416,255953,300186485,FRA,DESCHAMPS Didier (FRA),S,1,LLORIS,GKC,NaN

### 2.3.2 Conocer Valores unicos de  columna Event

In [ ]:
events = players_worldcups['Event'].unique()
print(len(events))

1894

In [ ]:
for event in events:
  print(event)
#11 events
#G ---> ?
#I ---> ?
#Y ---> ?
#W  ---> ?
#O  ---> ?
#IH  --> ?
#MP ---> ?
#R  ---> ?
#OH  ---> ?
#RSY --> ?
#P --->

nan
G40'
G70'
G43' G87'
G19'
G45'
G23'
G69'
G30'
G62'
G21'
G1'
R70'
G89'
G79'
G75'
G81'
W51'
G3' G65'
G65'
G85'
G60' G67'
G10' G15' G50'
G60'
G53'
G12' G55'
G8' G17' G80'
P42' G65'
G67' G83'
G37' G73'
G35'
G7'
G24'
G15'
G51'
G12' G13'
G56'
G69' G87'
G20'
G80' G85'
G20' G31'
G18' G67' G72'
G61'
G4'
G57'
G12'
G68'
G37'
G93'
G44'
G18'
G109'
P116'
G35' G39'
G11'
G31' G61'
G29'
G7' G43'
G66'
G48'
G9' G67'
G49'
G29' G43'
G66' G70' G87'
G25'
P18' G25'
G55'
G63'
G90'
G18' G29' G64'
G20' G69'
G50'
G67'
G82'
G78'
G60' G63'
P60'
G8'
R63'
G21' G69' G80'
G1' G42'
G54'
G27'
G28'
G95'
G71'
R96'
G43'
G13'
G28' G89'
G35' G76'
G16' G69'
G38'
G105'
G44' G103'
G88'
G94'
G2'
G83'
G44' G71'
P23'
G53' G59' G89' G118'
G18' G93' G104'
G111'
G118'
G75' G78'
G64'
W22'
G42'
R89'
R14'
P65'
G9' G81' G89'
G80'
G22' G37' G44'
G84'
G51' G72'
G10'
G9'
W19'
G39' G85'
G87'
G63' G74'
G16' G82'
G6' G35'
G30' G79'
G39'
G17'
G34'
G25' G69'
G59'
G17' G88'
G32'
G3'
G23' G51'
P89'
G74'
G26'
G23' G54'
G14' G40' G51'
G32' G60'
P48'
G16'
G47'
G37' G39'
G73'
P67'
G39' G88'
G17' G36' G52' G58'
Y1'
W15'
G31' G55'
G77' G85'
G5'
G33'
G34' G43'
G52'
G14'
G24' G36' G50'
G12' G89'
G75' G83'
W94'
G26' G63'
G36' G91'
G5' G71'
G54' G85'
G30' G83'
G17' G47' G57'
G4' G21' G24'
W46'
P88'
G3' G21' G69' G78'
G77'
G52' G54'
G76'
G10' G30'
G37' G64' G70'
P41'
G58'
G30' G60' G77'
G12' G79'
G14' G85'
G46'
G25' G27' G53'
G16' G39'
G26' G34'
G17' G19' G60'
W9'
P18'
R71'
G7' G88'
R79'
G61' G89'
P54' P64'
G31'
G75' G86'
G109' G116'
G22'
W59'
P16'
G18' G84'
G6'
P57'
G17' G64'
P85'
G32' G79'
G24' G30' G67'
G20' P44'
G38' G89'
G4' G85'
G63' G88'
P24'
P38'
G34' G55'
G3' G77'
G19' G60'
G19' G46'
G17' G40'
G82' G89'
G44' G99'
R102'
G55' G63'
R59'
G52' G64' G75'
G16' G36' G78' G89'
P27'
G55' G90'
G9' G32'
P19'
G44' G55'
P25'
G19' R71'
P17'
R41'
R8'
G8' G11'
G72'
G1' G6' G53'
G8' G70'
G72' G86'
P21'
G25' G87'
G20' G61'
P90'
G65' G67'
G31' G59'
G80' P84'
G9' G32' R83'
R80'
G47' G78'
P61'
G39' G52'
G20' P77'
G31' G88'
G2' G67'
G65' G79'
P15'
P73'
Y1' P26'
W17'
Y1' G38'
R65'
G27' G85'
G38' G75'
W43'
G28' G85'
Y1' R35'
R49'
G11' G83'
Y1' R54'
G27' P43' G56' P59'
Y1' G67'
R44'
P82'
G30' G80'
P12'
G18' G101' G120'
Y1' G78'
Y34'
Y30'
OH46'
O67'
Y1' O66'
I67'
IH46'
I66'
O12'
O57'
I57'
I12'
O29'
O59'
O51'
G49' O73'
I29'
I59'
I73'
I51'
O75'
O73'
I75'
O37'
O80'
O56'
I37'
I80'
I56'
O77'
OH45'
O72'
I72'
I77'
IH45'
G61' G83'
Y1' O62'
O46'
I46'
I62'
O79'
G12' G54'
P79'
I79'
O70'
I70'
O66'
O81'
G65' G75'
O76'
I81'
I76'
P75'
O69'
I69'
O34'
G14' G63'
G86'
I34'
Y38'
Y89'
Y72' O76'
O58'
G27' P52' G88'
I58'
Y1' O63'
O68'
O63'
I68'
I63'
G45' G46'
IH46' O76'
Y1' I58'
I76' G83'
O61'
O84'
I84' G90'
I61'
G19' G26' G39'
O27'
O74'
G34' O72'
G19' G67'
O60'
I60'
I27'
I74'
I86'
I82'
G51' G74'
Y67'
Y62'
Y90'
O42'
O50'
I42'
I50'
O65'
P50'
I65'
Y1' P14'
Y1' OH46'
G63' G76'
W25'
G13' O68'
Y1' IH46' G70'
I84'
Y1' G108'
O55'
G49' O81'
I55'
G75' O80'
O54'
G15' G52'
I54'
O86'
O71'
O96'
O103'
I103' G117'
I71'
I96'
Y1' O77'
G98'
I91' Y1'
G104'
Y1' G94' G110'
O53'
IH46' G111'
I53'
Y1' IH46'
Y1' I73'
G37' O84'
Y17'
Y49'
O83'
Y13' R67'
I83'
W58'
Y40' O78'
O64'
I64'
I78'
Y65'
Y50'
R69'
G7' G86'
Y25'
I70' G79'
Y1' G66'
G7' G62'
G8' O70'
O85'
I85'
G34' O67'
Y35'
Y56'
Y60'
O21'
R23'
G8' G30' G81'
I21'
Y36'
Y74'
Y86'
Y16'
I61' Y68'
Y44'
Y9'
O62'
G17' G87'
G30' G34' G50'
Y54'
Y48'
W35'
O78'
Y55'
Y60' G88'
Y24'
Y70'
O70' Y70'
I70' G81'
O82'
Y37' R83'
Y78'
O10'
I10' G79'
I59' Y77'
Y81'
Y84'
Y27' G77'
Y22' OH46'
Y5'
W78'
P5' P45' O79'
Y29'
I79' G88'
Y26'
G18' O57'
O52'
O25'
G15' G68'
I52'
I52' Y60'
I25'
G46' G77'
O43'
I43'
O33'
G38' O78'
I33'
IH46' Y71'
Y61'
Y27'
Y11' OH46'
Y28'
Y75'
Y22'
G10' G90'
Y58' O84'
Y44' O60'
IH46' Y72'
P24' O80'
O16'
I16'
O32'
I64' G76'
I32'
Y29' R84'
Y37'
G50' O85'
Y69'
Y68'
G14' O80'
Y23'
Y1' I70'
Y76'
Y71' O73'
Y3'
P2' Y39'
Y45'
G1' O74'
IH46' G54'
P45'
O88'
I88'
Y21' R89'
Y48' R88'
Y77'
I67' G83'
G9' O80'
Y19'
G43' O82'
G71' G77'
P40' G62' P79'
Y64'
G36' O83'
IH46' P81'
O39'
G44' G89'
G38' G73'
I39'
I64' O71'
O36'
P42'
I36'
G60' O89'
Y1' W43'
I89'
Y25' I46'
G41'
G42' O75'
G43' G84'
O6'
I6'
G41' O66'
P36' P39' G79'
P34'
Y1' P47' G68'
O44'
I44'
I10'
P35'
G36' G53'
G6' O66'
O11'
G15' G28'
Y80'
I70' P73'
I11'
G16' G71'
Y1' O86'
Y6'
Y1' I79' R88'
Y1' I34'
Y1' I67'
Y50' G75'
Y40' O77'
Y35' O65'
W18' G50'
G66' G87'
Y53' O77'
O7'
G57' G63'
I7' Y50'
G21' G48'
Y1' O51'
G50' G72'
I64' G67'
Y72'
Y35' G64'
Y40' O65'
G115'
Y15'
G38' G105'
Y96'
I65' Y93'
I59' G82'
I72' Y94'
Y47'
Y10'
O89'
O26'
G23' Y32' G54'
Y1' G4' G83'
I56' G69' G72' G76'
I68' G70'
I26' G64'
G29' G32'
I53' G79'
Y57'
G54' Y83' O88'
G1' G67'
O90'
I90'
Y12' O78'
Y66'
Y52'
G28' G57'
O24'
I24'
Y34' O66'
Y40'
Y17' IH46'
G24' O79'
Y11'
G9' G57' G66'
Y29' O66'
I79' G83'
W66'
Y87'
P14'
I63' G66'
G43' O81'
IH46' Y85'
I58' G60'
Y31'
G55' O74'
I26'
I74' G76'
Y79'
Y5' G86'
G84' O88'
G15' O71'
G54' O67'
Y20' O33'
P22'
G70' O75'
G28' G31'
G7' G31'
O31'
P59'
I31'
Y1' I58' G73'
R87'
I70' Y75' P84'
Y85'
G10' O69'
Y32'
Y43'
R62'
Y20'
Y42' O50'
Y41'
G39' O85'
O15'
I15'
G4' G26' G53'
Y39'
R84'
Y32' O58'
Y15' O80'
G27' G75'
IH46' G68'
O87'
I87'
R85'
G11' O83'
Y33'
IH46' G89'
Y83'
Y1' G75'
G33' G80'
Y59'
G46' G68' O83'
Y88'
Y13'
G5' G25' G74'
Y51'
O28'
Y57' O77'
G22' G73'
I28'
O97'
Y46'
G92'
Y40' O50'
P26'
G108'
Y35' G98'
I50' O60'
I97' G102'
Y61' O62'
Y73'
I7' G81' O89'
Y4'
Y82'
O13'
G2' O72'
P24' O69'
I62' W73'
I69' G80'
I13'
Y50' G73'
G6' G46'
O23'
I23'
Y33' O88'
G59' O71'
G6' Y79' O81'
Y58'
Y23' G39'
G45' O66'
G4' O80'
I56' Y62'
P6'
Y40' G62'
Y30' G53'
G11' O58'
IH46' G70'
O41'
I41' Y52' R85'
Y40' R42'
Y68' O76'
I41'
G18' O78'
I70' Y85'
G3' O77'
Y5' O62'
G68' O74'
Y42'
G16' O67'
Y1' Y52' RSY52'
Y16' P21'
Y7'
Y13' R19'
G11' G67' G80'
G52' O81'
I81' G88'
Y44' O74'
G29' O71'
I61' Y69' G84'
G58' O62'
I62' G74'
W82'
Y71'
Y31' O67'
Y17' OH46'
G17' G73'
G50' G76'
G19' G27'
I69' G79'
G9' G14' G34' O86'
O22'
I22'
Y12'
G15' G87'
O20'
I20'
R1'
Y62' O70'
P43' O71'
Y36' R88'
IH46' G62'
O112'
O99'
G110'
G27' G70' P111'
G102'
I99'
I112'
Y58' O61'
G79' Y83'
Y36' P83'
P30' O69'
G15' O85'
IH46' Y67'
G31' G72'
G56' O80'
Y27' P68'
P33' O71'
G43' G57' G80' P89'
Y26' O60'
Y60' O83'
O91'
I91'
Y94'
O115'
Y20' R100'
I115'
I32' Y75'
Y39' OH46'
O105'
Y115'
IH46' G85'
I105'
G51' G55'
I57' G90'
G51' G63'
Y63'
P111'
G84' O90'
Y21'
IH46' G81'
R61'
Y9' R88'
Y53'
Y27' O69'
G41' Y44' P55' O87'
Y5' O74'
I75' G78'
P40'
R52'
G26' G78'
I76' G90'
G40' G63'
G28' G64'
G9' O83'
I69' Y75'
P83'
Y55' O70'
IH46' G58' Y58'
Y68' O79'
R48'
Y73' G79'
Y77' O78'
I59' G76' G86'
I63' G88'
Y62' O80'
P31'
G46' O82'
G35' G75'
G37' O72'
Y16' O71'
P81'
I75' G86'
Y28' O52'
G43' Y68'
G23' G61' G81'
Y35' Y42' RSY42'
G15' OH46'
I56' G73'
Y8'
G68' O72'
G20' Y75'
I34' Y66'
IH46' G52'
Y36' Y76' RSY76'
G22' OH46'
G9' G46' Y76'
O35'
Y66' O78'
I35'
I78' G90'
Y44' G78'
Y28' O55'
R33'
G63' O84'
Y42' G83'
Y26' O70'
IH46' Y50'
I84' Y90'
Y8' O39'
I65' G81'
Y18' O81'
Y28' O60'
I60' G87'
Y23' OH46'
I62' G90'
I84' Y88'
Y117'
Y73' O79'
I54' G106' G108'
I79' G115'
Y5' G55'
G12' G63' G82'
Y50' O83'
Y20' R22'
Y21' R22'
G51' O77'
O94'
Y107'
O98'
Y21' O22'
Y112'
I94'
I75' Y116'
I98'
Y36' O52'
I52' G83'
Y110'
O49'
G78' G93'
Y92'
Y7' O79'
I49'
I79' Y98'
O107'
I71' G119'
I107'
Y42' O51'
Y24' R31'
I51' Y61'
Y14' O67'
Y11' R70'
Y105'
P83' P105'
Y119'
G67' Y82'
Y30' Y103' RSY103'
Y22' O73'
I99' Y120'
G60' Y110'
O38'
Y98'
I38'
P86'
Y5' R87'
IH46' R65'
Y37' O59'
G51' O63'
R25'
I59' G90'
Y39' O66'
I79' R82'
G44' O58'
I72' Y82'
G11' O68'
Y50' O90'
G15' Y39' G89' O90'
I78' G84'
Y72' G75'
G31' O81'
G18' Y61'
O45'
I57' G86'
I45'
P52'
G2' G44' P90'
G60' O83'
G55' Y73'
Y54' O59'
G14' O64'
Y40' O85'
G16' O71'
G65' G72'
I70' R73'
G52' I66'
Y24' I46'
R21'
Y34' O68'
Y22' Y82' RSY82'
G42' G65'
Y45' O80'
I67' G84'
Y1' Y49' RSY49'
O40'
P4'
Y58' G59' G81'
P37'
Y41' O84'
I40'
Y20' O61'
IH46' Y49'
G45' Y75'
P7' O79'
G21' G28' Y54'
G8' O56'
P5' P55'
Y6' O58'
Y42' O48'
I82' Y84' G90'
I48' Y59'
G18' Y73'
Y62' O83'
G44' Y58' O78'
Y39' O81'
G12' Y28' G37'
Y44' O75'
P19' O68'
G66' G70' Y90'
I75' Y83'
Y63' O83'
IH46' G48'
G15' G41' P44' G72' G75'
O48'
IH46' G46'
I64' G81'
I48'
Y14'
Y12' G47'
Y25' OH46'
I67' G77'
G5' O63'
G45' O83'
Y32' O71'
Y45' Y67' RSY67'
Y7' G61'
Y44' O67'
Y38' G90'
G6' G40'
G11' O85'
G15' O76'
Y18' O61'
I76' Y87'
I61' P86'
I73' Y77'
I58' Y69'
Y67' O70'
G51' G88'
I54' G85'
I63' Y71'
G58' O85'
G11' G18' Y84' O88'
Y43' OH45'
R43'
Y64' Y85' RSY85'
G88' P102'
G25' O57'
Y2'
Y60' O63'
IH46' Y62'
I35' Y41'
I63' R75'
Y12' Y50' RSY50'
O119'
P18' Y76'
Y17' O104'
Y28' Y57' RSY57'
I104'
I119'
Y19' G58'
G81' O90'
Y40' G76'
Y49' O82'
G75' Y82' O84'
P47'
Y15' O58'
Y43' Y101' RSY101'
G88' G101'
I84' Y108'
Y52' O71'
G21' G25' O71'
P44' O78'
G37' O79'
G40' Y82'
O106'
O95'
I34' Y41'
I21' Y87'
I95'
I106'
W74'
G5' Y37'
Y25' O78'
G60' O86'
W45' O78'
Y53' O82'
Y8' O61'
G45' G48'
P84'
G11' O71'
Y30' O65'
Y27' Y89' RSY89'
Y60' G69'
Y12' O65'
I65' Y73'
Y28' O73'
W77'
I26' G36'
W73'
Y59' O77'
IH46' Y56'
Y27' O70'
G75' G84'
G27' R30'
Y26' OH46'
IH46' G50'
R82'
I22' Y30'
Y60' O68'
G45' O74'
Y59' O74'
I65' Y70'
G10' O89'
I50' Y77'
Y58' O81'
Y56' O61'
G46' O60'
Y36' O68'
Y64' O76'
Y32' O88'
G45' O87'
G50' O72'
Y58' G70'
Y16' O69'
Y47' O56'
I73' G90'
R42'
G7' Y63'
G75' G89'
Y28' O88'
Y23' O82'
I58' R66'
IH45' Y65' R68'
I82' R85'
Y50' G85'
Y7' O76'
R19'
G37' G78' O79'
O30'
I33' O65'
I30' G68'
O66' Y66'
G28' Y49' O75'
I65' Y87'
Y26' O67'
Y83' O88'
G42' G47'
P55' O67'
Y47' G62'
R28'
O17'
I17' R54'
G83' O84'
G71' O77'
I69' Y90'
I77' G80'
W72'
IH46' Y75'
G73' G78' P83'
Y4' Y45' RSY45'
IH46' Y88'
Y18'
O77' Y77'
I56' G82'
G46' O86'
Y4' O72'
I72' O81'
I72' G81'
O4'
G48' O60'
I4'
I80' P90'
I72' G90'
Y55' O77'
Y8' R51'
G20' O70'
Y66' O70'
I77' Y89'
I82' R88'
R53'
G23' G85'
Y81' O87'
Y61' G83'
G56' O64'
IH46' Y65'
I75' Y78'
Y38' O67'
G18' P90'
P74' O81'
G55' G81'
G18' O69'
Y85' W88'
I28' Y45'
I69' Y73'
I65' G90'
G58' O67'
Y46' O71'
Y46' G90'
I55' Y68' G75'
Y45' O69'
Y31' G57'
Y41' O54'
I30' Y61'
G39' G54'
G36'
Y23' O52'
P12' Y57' O90'
I68' G71'
Y20' OH46'
G20' O79'
IH46' Y86'
Y38' O63'
Y35' O73'
I13' O39'
G11' G26'
P45' G72'
G114'
Y99'
G12' O77'
G3' O58'
I73' G77'
G58' I58'
Y38' O56'
Y70' O75'
I91' Y47'
R47'
P5' O68'
P9'
I97'
Y113'
Y53' O65'
Y19' O87'
G25' G59' O87'
G10' O64'
Y22' O89'
Y17' Y76' RSY76'
Y86' R87'
R40'
Y57' G85'
G80' O83'
Y48' O56'
O111'
I111' Y119'
I75' Y90'
R76'
Y75' O89'
G47' G70'
G14' O79'
Y48' Y68' RSY68'
G27' G45'
Y56' O57'
G47' O87'
Y34' O58'
G45' G83'
Y30' OH45'
G39' O69'
IH45' Y51'
I77' Y82'
G45' O67'
G20' G25' G70' O76'
G63' O81'
O73' Y73'
Y9' O27'
Y38' O78'
I86' Y90'
Y12' G24'
P87'
Y36' G74'
I57' Y65' G82'
Y44' R86'
G50' O73'
Y24' RSY90' Y90'
I67' Y73'
Y54' O85'
G7' G27'
P60' O79'
G61' Y79'
Y54' G67'
G59' O68'
Y21' G75'
G53' O61'
G26' O50'
I89' Y90'
Y27' OH45'
Y50' O67'
P64'
I78' Y88'
W29' O73'
W71'
Y34' G39'
G19' O85'
P16' Y20'
G52' Y62' R80'
I46' O83'
I62' Y84'
Y10' O84'
I35' Y59'
Y47' O60'
Y45' O71'
G35' P63'
Y13' O60'
P44'
Y50' O54'
O19'
I19'
W10'
IH45' G53' G69'
G4' O71'
G55' O72'
Y25' P45' O46'
G76' O79'
Y51' G55'
I57' G73'
Y45' O88'
G56' Y89'
I77' G86'
G51' O85'
Y13' OH45'
I72' Y90'
G57' Y65'
G28' O77'
Y15' O53'
G5' Y87'
I53' Y61'
G24' O82'
MP40'
I56' G78'
G14' G65' G77'
Y25' O63'
I60' G88'
I16' Y39'
Y22' O67'
Y69' O88'
Y27' O76'
Y8' O54'
Y2' O67'
P20' Y87'
Y39' O63'
Y8' OH46'
G26' G38' Y69'
G45' IH46'
I63' Y87'
IH46' G69'
Y44' O53'
Y37' Y40' RSY40'
Y9' OH45'
G79' O84'
Y58' O64'
I53' Y60' Y77' RSY77'
IH45' G50'
Y58' O63'
Y78' O88'
MP88'
I63' Y75'
I58' G88'
R45'
Y15' O40'
G45' O62'
Y4' Y22' RSY22'
I53' G73'
I40' Y69'
I62' R81'
I61' G65' G84' O90'
G4' G56' O82'
Y69' O74'
G53' O80'
G10' G13'
G62' O72'
G6' Y81'
I46' R58'
Y10' O63'
G34' O80'
Y43' O78'
I78' G85'
I55' Y57'
G75' O84'
I46' G48'
R27'
O90' Y90'
Y22' Y66' RSY66'
Y63' O65'
G3' Y86' O86'
MP76'
I65' G66'
Y14' O34'
I70' G78'
I43' Y84'
I34' G88'
Y24' O58'
G22' O46'
G44' O69'
I7'
G88' O90'
Y26' R90'
I60' Y71'
G8' O72'
G37' G104'
G67' O90'
R88'
Y37' OH45'
Y47' O90'
Y50' O59'
G8' O79'
I78' Y81'
I28' Y67'
G12' O74'
I46' O86'
Y17' O63'
Y22' Y13' RSY13'
MP5' G27'
I68' Y9'
G23' O79'
G50' R57'
Y69' O80'
I60' Y68'
Y22' O91'
I67' Y87' G4'
O93'
Y52' O60'
Y111'
Y53' O70'
I93'
Y85' O88'
Y71' G75'
I56' Y90'
G49' O68'
G9' Y23' O65'
G13' G32'
Y9' O74'
G67' G79' O90'
G17' G61' O79'
G12' G73'
Y31' O69'
G24' O65'
O8'
W2'
I8'
Y15' Y46' RSY46'
G38' Y41' O75'
G82' Y90'
G24' O64'
I75' Y81'
I43' Y64'
Y18' OH46'
G28' G76'
IH46' G79'
I53' Y69' G84' G89'
I56' Y68' O90'
I75' Y78' G90'
G5' O45'
G36' G76' Y81' O86'
I45' Y59'
Y65' O89'
I64' G83' Y88'
Y23' Y53' RSY53'
Y51' G54'
I46' G72'
Y45' O56'
Y32' O41'
G13' O55'
G17' P48' O55'
Y79' O82'
Y36' O55'
Y65' O69'
G57' O82'
I82' G84'
Y28' Y75' RSY75'
Y3' O77'
I71' G90'
I64' Y68'
G8' OH46'
IH46' G90'
Y45' O70'
Y18' O85'
I81' Y85'
I46' Y60'
Y7' O50'
Y36' G78'
G6' G41' O75'
Y27' O46'
I17' G31'
I59' G84'
I75' G88'
G27' O73'
G38' O62'
IH46' Y90'
Y44' Y79' RSY79'
Y59' O78'
O88' Y88'
P80'
Y48' G63' O80'
Y32' O66'
G2' Y66' O85'
G82' Y84'
W27' O54'
Y5' O35'
Y21' Y47' RSY47'
Y69' O87'
G49' O88'
Y31' O72'
I88' G90'
I72' Y83'
Y85' O90'
Y11' O69'
G16' O87'
I25' Y45'
Y41' O55'
G36' O71'
Y77' G84'
G76' P90'
G8' Y90'
Y32' O57'
I80' Y81'
IH46' G71'
I46' Y89'
G4' G44' O66'
Y52' O63'
I66' Y75'
G25' Y45' O82'
Y18' O64'
G33' G66'
G51' O75'
I69' G85'
W25' Y45'
Y48' O67'
I66' G86'
I51' G60'
Y26' O61'
G6' Y69'
Y27' Y61' RSY61'
IH46' Y87'
I80' Y88'
P37' Y43' G67'
Y41' Y90' RSY90'
Y33' O73'
G10' O67'
I73' P86'
I16' Y17' Y45' RSY45'
Y35' Y45' RSY45'
I17' G26'
Y7' O74'
P45' Y90'
G22' O80'
G45' G81'
Y44' G59'
I60' O66'
Y61' Y90' RSY90'
Y32' Y85' RSY85'
Y81' Y87' RSY87'
Y9' RSY45' Y45'
P70' O88'
Y43' O79'
Y27' O68'
Y35' O70'
I13' Y77'
G55' O81'
Y44' O59'
G23' Y43' O53'
Y23' O66'
Y55' O71'
I53' Y90'
I63' Y78'
Y28' Y35' RSY35'
Y27' O85'
G4' G12' O74'
Y48' O52'
I72' Y78'
G6' Y70'
G10' O75'
I38' Y118'
G60' O87'
Y37' O72'
Y7' Y63' RSY63'
Y31' Y45' RSY45'
Y60' O84'
Y59' Y90' RSY90'
Y20' G23'
Y73' Y78' RSY78'
I46' Y50'
I56' Y74'
R50'
I75' P90'
O117'
I111'
I117'
Y48' Y81' RSY81'
Y13' G45' O61'
Y38' O60'
Y68' G83'
Y90' G90'
P28' O54'
G41' Y87'
Y114'
G80' O86'
I79' Y95'
I62' Y90'
G59' G69'
Y67' O72'
Y16' O20'
I52' O119'
Y25' O76'
G57' O86'
I86' Y87'
G119'
Y90' O91'
Y40' O73'
O104'
I104' G120'
P33'
I85' Y87'
G56' G78' Y78' O79'
Y33' OH46'
IH46' W60'
I69' G88'
P7' R110'
O100'
I100'
IH46' Y70'
I63' Y65' Y81' RSY81'
Y26' O31'
G4' Y61'
Y74' O77'
IH46' Y60'
Y35' O87'
I58' Y59' Y73' RSY73'
I87' Y90'
P85' O90'
Y54' Y74' RSY74'
Y19' O69'
I62' Y83'
R56'
Y12' O74'
G8' O81'
G26' O68'
I68' G70' Y90'
Y44' O88'
Y49' O77'
I59' Y70'
G90' Y90'
G50' O84'
G72' O73'
I79' Y90'
Y6' O79'
G24' P80'
G33' G76' G80' O82'
W17' O81'
Y34' G45'
Y15' O37'
I37' Y88'
IH46' Y89'
I55' O77'
Y4' O62'
Y48' O55'
I62' P79'
I55' G64'
MP60'
G38' O79'
Y12' Y37' RSY37'
G42' O74'
G13' O87'
Y40' OH46'
I74' O90'
G53' O83'
R24'
Y49' O72'
G27' Y45' O88'
Y47' O70'
P29'
Y14' O63'
G62' O67'
G25' G50'
Y85' Y88' RSY88'
I68' Y75'
G53' O74'
G29' O70'
G56' Y70' O77'
G60' G89'
I77' G81'
Y2' OH46'
Y18' O68'
Y60' O65'
R31'
I42' Y48'
IH46' G75'
G17' G51' MP62'
Y8' O63'
G43' O85'
I57' Y86'
I63' Y77'
G49' O90'
P69' O70'
Y30' O54'
I80' G89'
G23' O86'
I62' Y81'
Y76' Y90' RSY90'
I80' Y90'
Y43' O67'
Y40' O90'
Y50' O82'
I66' G73'
Y16' O87'
G25' Y40' G73' O90'
IH46' Y83' G90'
I87' G89'
MP81' G81'
Y12' G30' O90'
Y29' O56'
I74' G87'
Y25' O73'
Y17' O66'
G36' O59'
Y65' O73'
I59' G83'
Y25' O54'
Y43' O44'
Y40' O64'
Y15' O85'
I64' G82'
Y21' Y37' RSY37'
IH46' G47'
Y34' OH46'
Y58' O87'
G8' G80' O84'
P62'
O113'
Y7' O31'
G5' O78'
I113'
G20' O72'
G67' G70' O72'
G26' G52' O69'
G18' Y31' O71'
I71' Y72'
G38' O76'
Y30' O81'
G59' O85'
I62' Y80'
Y58' O65'
Y118'
OH106'
IH106'
G63' O88'
Y74' O90'
R73'
Y37' O62'
G53' G68'
MP120'
Y93'
R120'
G45' O88'
G68' G89'
G3' Y35' O84'
Y11' O70'
MP59'
Y59' O84'
MP62' O75'
G41' O84'
Y29' G70'
Y21' G90'
G73' O89'
G56' O81'
G28' O88'
Y61' O77'
Y7' O73'
Y57' RSY109' Y109'
G116' Y118'
Y54' O105'
Y120'
Y28' O99'
W11'
Y27' G29' P71' O88'
G61' O74'
IH46' Y77'
Y41' G65' O77'
P27' O62'
Y25' O62'
G44' Y66' G72' O79'
G53' G80'
G35' Y44'
G14' O68'
I68' G90'
G5' O74'
Y55' O57'
G58' O76'
Y56' O60'
R90'
I83' G84'
G37' O80'
G64' O78'
I75' G90'
W48'
Y28' Y43' RSY43'
Y45' O65'
Y28' O57'
IH46' Y53'
W3'
G32' O73'
R37'
P12' G45' G78' O82'
Y30' O71'
IH46' G86'
I65' G70'
IH46' G80'
Y45' OH46'
Y13' O84'
Y49' O59'
I56' G68'
I71' G74'
G21' Y43' O69'
P54'
Y47' G58' O87'
I45' G68'
Y41' OH46'
Y26' O88'
G20' O85'
G43' O64'
G48' O78'
G61' G73'
G11' O69'
I69' Y89'
I53' G70'
G39' G85' O88'
Y12' OH46'
Y27' Y38' RSY38'
G44' O81'
I68' Y71'
O9'
G40' O82'
G17' O63'
MP32' G67'
I9'
Y80' O90'
G34' G65' Y73'
Y73' O76'
G51' O69'
I69' G71'
Y6' O64'
I57' G88'
Y67' O89'
G62' O77'
Y69' O78'
G38' O73'
G81' O87'
G64' Y75'
I69' G90'
G36' O56'
Y25' O70'
I75' G77'
G17' G35' O71'
IH46' G84'
I58' Y75'
Y39' G72'
I69' R89'
I62' G82'
Y57' O62'
P17' OH46'
G45' O69'
G55' G82'
Y37' O78'
I61' G74'
I12' G42'
G4' G47'
G3' G45' O63'
G23' O84'
I68' Y88'
G6' G31' G71' O87'
I40' Y66'
W31'
I71' Y78'
G60' O90'
I77' Y87'
O108'
I87' Y102'
I108'
I64' Y93'
G28' G50' O85'
W90'
O109'
G120'
Y42' O97'
IH46' G92'
I109'
I100' G120'
G7' Y64'
Y67' P80'
G29' O76'
G23' O58'
G24' G26'
I58' G69' G79'
G17' O70'
P3'
IH46' Y54'
O120'
I120'
I88' G113'
O101'
I101'
I96' Y105'
Y64' O106'
I106' Y111'
Y53' O75'
G48' O61'
I76' P90'
Y42' Y66' RSY66'
G52' Y70'
Y48' O66'
Y36' O58'
Y36' O66'
G118' Y120'
Y90' O105'
I66' Y73'
I91' G105'
I105' G107'

In [ ]:
players_worldcups.size

340056

In [ ]:
#Using the dataframe of matches we can found the match using MatchID and then search in internet what happen about the Event in that minute
matches_worldcups.loc[matches_worldcups['MatchID'] == 300186457	]
#G ---> Goal
#I ---> In (Ingresar)
#Y ---> Yellow card
#W  ---> OWN Goal (Auto gol)
#O  ---> OUT (Salio)
#IH  --> IN HALF TIME (Ingresar al segundo timpo) IH46
#MP ---> MISSING PENALTY(Penalti perdido)
#R  ---> RED CARD (Tarjeta Roja)
#OH  ---> OUT HALF ITME (Salir al segundo tiempo) OH46
#RSY --> RED CARD BY TWO YELLOW CARDS (Expulsado x dos amarillas)
#P ---> Penal Gol

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
810,2014.0,24 Jun 2014 - 16:00,Group C,Arena Pantanal,Cuiaba,Japan,1.0,4.0,Colombia,,40340.0,1.0,1.0,PROENCA Pedro (POR),MIRANDA Bertino (POR),TRIGO Jose (POR),255931.0,300186457.0,JPN,COL

### 2.3.3 Conocer Valores unicos de  columna Line Up

In [ ]:
players_worldcups['Line-up'].unique()
#Solo son dos valores me imagino que uno es Inicialista y el otro es banca

array(['S', 'N'], dtype=object)

Vamos a usar la final del mundial 2014 para verificar los inicialistas y los subtitutos

In [ ]:
players_worldcups.loc[(players_worldcups['MatchID'] == 300186501) ]
#Vemos que jugadores como Messi , Never  tiene S en line up el cual es inicialista
# S ---> inicialista
# N ----> Sustituto
#Los que entran como subtitutos tienen Event --> IH46' O I{Tiempo}'
#Estamos viendo que existen valores repetidos en nuestro dataframe teniendo en cuenta todas las columnas

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
36680,255959,300186501,GER,LOEW Joachim (GER),S,1,NEUER,GK,NaN
36681,255959,300186501,ARG,SABELLA Alejandro (ARG),S,1,ROMERO,GK,NaN
36682,255959,300186501,GER,LOEW Joachim (GER),S,4,HÔøΩWEDES,NaN,Y34'
36683,255959,300186501,ARG,SABELLA Alejandro (ARG),S,2,GARAY,NaN,NaN
36684,255959,300186501,GER,LOEW Joachim (GER),S,5,HUMMELS,NaN,NaN
...,...,...,...,...,...,...,...,...,...
37779,255959,300186501,ARG,SABELLA Alejandro (ARG),N,19,ALVAREZ,NaN,NaN
37780,255959,300186501,GER,LOEW Joachim (GER),N,6,KHEDIRA,NaN,NaN
37781,255959,300186501,ARG,SABELLA Alejandro (ARG),N,20,AGUERO,NaN,IH46' Y65'
37782,255959,300186501,GER,LOEW Joachim (GER),N,21,MUSTAFI,NaN,NaN
37783,255959,300186501,ARG,SABELLA Alejandro (ARG),N,23,BASANTA,NaN,NaN

### 2.3.4 Drop row duplicates
Hemos encontrado que en el dataframe original de matches existen filas duplicadas por ende debemos eliminarlas

In [ ]:
players_worldcups.shape

(37784, 9)

In [ ]:
players = players_worldcups.drop_duplicates()
print(f'Tama√±o df original {players_worldcups.shape},Tama√±o del df sin duplicados {players.shape}')

Tama√±o df original (37784, 9),Tama√±o del df sin duplicados (37048, 9)

In [ ]:
players.loc[(players['MatchID'] == 300186501) ]

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
36680,255959,300186501,GER,LOEW Joachim (GER),S,1,NEUER,GK,NaN
36681,255959,300186501,ARG,SABELLA Alejandro (ARG),S,1,ROMERO,GK,NaN
36682,255959,300186501,GER,LOEW Joachim (GER),S,4,HÔøΩWEDES,NaN,Y34'
36683,255959,300186501,ARG,SABELLA Alejandro (ARG),S,2,GARAY,NaN,NaN
36684,255959,300186501,GER,LOEW Joachim (GER),S,5,HUMMELS,NaN,NaN
36685,255959,300186501,ARG,SABELLA Alejandro (ARG),S,4,ZABALETA,NaN,NaN
36686,255959,300186501,GER,LOEW Joachim (GER),S,7,SCHWEINSTEIGER,NaN,Y29'
36687,255959,300186501,ARG,SABELLA Alejandro (ARG),S,6,BIGLIA,NaN,NaN
36688,255959,300186501,GER,LOEW Joachim (GER),S,8,ÔøΩZIL,NaN,O120'
36689,255959,300186501,ARG,SABELLA Alejandro (ARG),S,8,PEREZ,NaN,O86'
36690,255959,300186501,GER,LOEW Joachim (GER),S,11,KLOSE,NaN,O88'
36691,255959,300186501,ARG,SABELLA Alejandro (ARG),S,9,HIGUAIN,NaN,O78'
36692,255959,300186501,GER,LOEW Joachim (GER),S,13,MÔøΩLLER,NaN,NaN
36693,255959,300186501,ARG,SABELLA Alejandro (ARG),S,10,MESSI,C,NaN
36694,255959,300186501,GER,LOEW Joachim (GER),S,16,LAHM,C,NaN
36695,255959,300186501,ARG,SABELLA Alejandro (ARG),S,14,MASCHERANO,NaN,Y64'
36696,255959,300186501,GER,LOEW Joachim (GER),S,18,KROOS,NaN,NaN
36697,255959,300186501,ARG,SABELLA Alejandro (ARG),S,15,DEMICHELIS,NaN,NaN
36698,255959,300186501,GER,LOEW Joachim (GER),S,20,BOATENG,NaN,NaN
36699,255959,300186501,ARG,SABELLA Alejandro (ARG),S,16,ROJO,NaN,NaN
36700,255959,300186501,GER,LOEW Joachim (GER),S,23,KRAMER,NaN,O31'
36701,255959,300186501,ARG,SABELLA Alejandro (ARG),S,22,LAVEZZI,NaN,OH46'
36702,255959,300186501,GER,LOEW Joachim (GER),N,12,ZIELER,GK,NaN
36703,255959,300186501,ARG,SABELLA Alejandro (ARG),N,12,ORION,GK,NaN
36704,255959,300186501,GER,LOEW Joachim (GER),N,22,WEIDENFELLER,GK,NaN
36705,255959,300186501,ARG,SABELLA Alejandro (ARG),N,21,ANDUJAR,GK,NaN
36706,255959,300186501,GER,LOEW Joachim (GER),N,2,GROÔøΩKREUTZ,NaN,NaN
36707,255959,300186501,ARG,SABELLA Alejandro (ARG),N,3,CAMPAGNARO,NaN,NaN
36708,255959,300186501,GER,LOEW Joachim (GER),N,3,GINTER,NaN,NaN
36709,255959,300186501,ARG,SABELLA Alejandro (ARG),N,5,GAGO,NaN,I86'
36710,255959,300186501,GER,LOEW Joachim (GER),N,9,SCHÔøΩRRLE,NaN,I31'
36711,255959,300186501,ARG,SABELLA Alejandro (ARG),N,7,DI MARIA,NaN,NaN
36712,255959,300186501,GER,LOEW Joachim (GER),N,10,PODOLSKI,NaN,NaN
36713,255959,300186501,ARG,SABELLA Alejandro (ARG),N,11,M. RODRIGUEZ,NaN,NaN
36714,255959,300186501,GER,LOEW Joachim (GER),N,14,DRAXLER,NaN,NaN
36715,255959,300186501,ARG,SABELLA Alejandro (ARG),N,13,A. FERNANDEZ,NaN,NaN
36716,255959,300186501,GER,LOEW Joachim (GER),N,15,DURM,NaN,NaN
36717,255959,300186501,ARG,SABELLA Alejandro (ARG),N,17,F. FERNANDEZ,NaN,NaN
36718,255959,300186501,GER,LOEW Joachim (GER),N,17,MERTESACKER,NaN,I120'
36719,255959,300186501,ARG,SABELLA Alejandro (ARG),N,18,PALACIO,NaN,I78'
36720,255959,300186501,GER,LOEW Joachim (GER),N,19,GÔøΩTZE,NaN,I88' G113'
36721,255959,300186501,ARG,SABELLA Alejandro (ARG),N,19,ALVAREZ,NaN,NaN
36722,255959,300186501,GER,LOEW Joachim (GER),N,6,KHEDIRA,NaN,NaN
36723,255959,300186501,ARG,SABELLA Alejandro (ARG),N,20,AGUERO,NaN,IH46' Y65'
36724,255959,300186501,GER,LOEW Joachim (GER),N,21,MUSTAFI,NaN,NaN
36725,255959,300186501,ARG,SABELLA Alejandro (ARG),N,23,BASANTA,NaN,NaN

Falta mirar como tratar los NA
Quizas de esta forma
- Position ---> Posici√≥n desconocida
- Event --> Sin evento

### 2.3.5 Encontrar insights
- Top 10 goleadores mundiales
- Top 5 mas goles en un partido
- Top 10 jugadores con mas partidos
- Top 5 Capitanes con mas goles
- Top 5 Capitanes con mas partidos
- Top jugadores con mas amarillas
- Top jugadores con mas rojas
- Jugadores que entraron de cambio e hicieron gol
- Jugadores con mas autogoles

Top 10 goleadores mundiales

In [ ]:
#Crear funci√≥n para que me cree columna con el n√∫mero de goles por partido
def cantidad_goles(cadena):
    return cadena.count('G') + cadena.count('P')

In [ ]:
df_players_events = players.dropna(subset = ['Event']) #Eliminar registros sin eventos

In [ ]:
print(f'Tama√±o df original {df_players_events.shape},Tama√±o del df sin duplicados {players.shape}')

Tama√±o df original (8823, 9),Tama√±o del df sin duplicados (37048, 9)

In [ ]:
df_players_events['Goals'] = df_players_events['Event'].apply(cantidad_goles) #Crear columna goles donde salgan los goles por partido

<ipython-input-12-dbd6ba52e21b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_events['Goals'] = df_players_events['Event'].apply(cantidad_goles) #Crear columna goles donde salgan los goles por partido

In [ ]:
#Top 10 goleadores mundiales
df_players_events.get(['Player Name','Team Initials','Goals']).groupby(['Player Name','Team Initials'],as_index=False).sum().sort_values(by='Goals',ascending=False).head(10)

                             Player Name Team Initials  Goals
2086                               KLOSE           GER     16
3141                             RONALDO           BRA     15
1338                        Gerd MUELLER           FRG     14
2004                       Just FONTAINE           FRA     13
2921  PELÔøΩ (Edson Arantes do Nascimento)           BRA     12
3472                       Sandor KOCSIS           HUN     11
2683                              MÔøΩLLER           GER     11
754                          DAVID VILLA           ESP     10
1313                        Gary LINEKER           ENG     10
3652                    Teofilo CUBILLAS           PER     10

Top 5 mas goles en un partido

In [ ]:
df_players_events.sort_values(by='Goals',ascending=False).head(5)

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Goals
21540,337,3079,RUS,SADYRIN Pavel (RUS),S,9,Oleg SALENKO,NaN,G15' G41' P44' G72' G75',5
17492,309,511,ESP,MUNOZ Miguel (ESP),S,9,Emilio BUTRAGUENO,NaN,G43' G57' G80' P89',4
8357,239,1702,POR,GLORIA Otto (BRA),S,13,EUSEBIO (Eusebio da Silva Ferreira),NaN,G27' P43' G56' P59',4
3609,211,1277,HUN,SEBES Gusztav (HUN),S,8,Sandor KOCSIS,NaN,G3' G21' G69' G78',4
2881,209,1189,BRA,COSTA Flavio (BRA),S,0,ADEMIR,NaN,G17' G36' G52' G58',4

Top 10 jugadores con mas partidos

In [ ]:
#S --> Inicialista
#Event --> I or IH46 --> Jugo
#Puedo Crear columna llamada matches y contar por Line-up y or Event --> I Or IH46
players.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN

In [ ]:
df_players_matchs = players

In [ ]:
df_players_matchs['Matchs_Line-Up'] = df_players_matchs['Line-up'].map({'S':1 ,'N':0})

<ipython-input-324-d9f93539e119>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_matchs['Matchs_Line-Up'] = df_players_matchs['Line-up'].map({'S':1 ,'N':0})

In [ ]:
df_players_matchs.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Matchs_Line-Up
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN,1
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN,1
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40',1
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70',1
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN,1

In [ ]:
df_players_matchs['Event'] = df_players_matchs['Event'].fillna('N/A')

<ipython-input-326-44804112bae1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_matchs['Event'] = df_players_matchs['Event'].fillna('N/A')

In [ ]:
df_players_matchs.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Matchs_Line-Up
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,N/A,1
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,N/A,1
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40',1
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70',1
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,N/A,1

In [ ]:
#Crear funci√≥n para que me cree columna con 1 si entro de cambio  o con 0 si se quedo en la banca
def cantidad_partidos(cadena):
    return cadena.count('I')

In [ ]:
df_players_matchs['Matchs_Event'] = df_players_matchs['Event'].apply(cantidad_partidos)

<ipython-input-329-d0faba3b1b67>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_matchs['Matchs_Event'] = df_players_matchs['Event'].apply(cantidad_partidos)

In [ ]:
df_players_matchs['Matchs'] = df_players_matchs['Matchs_Line-Up'] + df_players_matchs['Matchs_Event']

<ipython-input-332-cd593ef4b5be>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_matchs['Matchs'] = df_players_matchs['Matchs_Line-Up'] + df_players_matchs['Matchs_Event']

In [ ]:
df_players_matchs.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Matchs_Line-Up,Matchs_Event,Matchs
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,N/A,1,0,1
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,N/A,1,0,1
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40',1,0,1
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70',1,0,1
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,N/A,1,0,1

In [ ]:
df_players_matchs.get(['Player Name','Team Initials','Matchs']).groupby(['Player Name','Team Initials'],as_index=False).sum().sort_values(by='Matchs',ascending=False).head(10)
#Top 10 jugadores ocn mas partidos

                Player Name Team Initials  Matchs
4130                  KLOSE           GER      24
1728         Diego MARADONA           ARG      21
7228             Uwe SEELER           FRG      21
7587        Wladyslaw ZMUDA           POL      21
4324                   LAHM           GER      20
4223  Karl-Heinz RUMMENIGGE           FRG      20
1123                   CAFU           BRA      20
2747          Grzegorz LATO           POL      20
5274                 MÔøΩLLER           GER      20
6564         SCHWEINSTEIGER           GER      20
6122                RONALDO           BRA      19
5540                  OSCAR           BRA      19
7599       Wolfgang OVERATH           FRG      19
4796            MERTESACKER           GER      19
979             Berti VOGTS           FRG      19

Top 10 capitanes con mas goles

In [ ]:
goles_capitanes = df_players_events.loc[(df_players_events['Position'].isin(['GKC','C']))&(df_players_events['Goals']==1)]

In [ ]:
goles_capitanes.get(['Player Name','Team Initials','Goals']).groupby(['Player Name','Team Initials'],as_index=False).sum().sort_values(by='Goals',ascending=False).head(10)

           Player Name Team Initials  Goals
93          Uwe SEELER           FRG      5
44       Jan CEULEMANS           BEL      4
53     Kazimierz DEYNA           POL      4
61      Michel PLATINI           FRA      4
101             ZIDANE           FRA      3
12   Daniel PASSARELLA           ARG      3
36       Hans SCHAEFER           FRG      3
50   Juergen KLINSMANN           GER      3
32       Gyorgy SAROSI           HUN      3
33                HAGI           ROU      3

Top 5 capitanes con mas partidos

In [ ]:
capitans_matchs = df_players_matchs.loc[(df_players_matchs['Position'].isin(['GKC','C']))]

In [ ]:
capitans_matchs.get(['Player Name','Team Initials','Matchs']).groupby(['Player Name','Team Initials'],as_index=False).sum().sort_values(by='Matchs',ascending=False).head(5)

         Player Name Team Initials  Matchs
100   Diego MARADONA           ARG      16
103        Dino ZOFF           ITA      14
254  Kazimierz DEYNA           POL      13
261             LAHM           GER      13
462       Uwe SEELER           FRG      12

Top 5 jugador con mas amarillas en mundiales

In [ ]:
def cantidad_amarillas(cadena):
  contador = cadena.count('Y')
  if contador >2:
    return contador - 1
  else:
    return contador

In [ ]:
def cantidad_rojas(cadena):
    return cadena.count('R')

In [ ]:
df_players_events['Yellow_Cards'] = df_players_events['Event'].apply(cantidad_amarillas)

<ipython-input-205-a6d9dd7c43de>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_events['Yellow_Cards'] = df_players_events['Event'].apply(cantidad_amarillas)

In [ ]:
df_players_events['Red_Cards'] = df_players_events['Event'].apply(cantidad_rojas)

<ipython-input-206-39f1a196ec21>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_players_events['Red_Cards'] = df_players_events['Event'].apply(cantidad_rojas)

In [ ]:
df_players_events.loc[(df_players_events['Event'].str.contains(pat='Y'))]

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Yellow_Cards,Red_Cards
2915,209,1186,BRA,COSTA Flavio (BRA),S,0,BIGODE,NaN,Y1',1,0
5857,231,1447,ARG,LORENZO Juan Carlos (ARG),S,15,Ruben NAVARRO,C,Y1',1,0
7256,238,1596,BUL,VYTLACIL Rudolf (TCH),S,6,Dobromir JECHEV,NaN,Y1',1,0
7257,238,1596,BRA,FEOLA Vicente (BRA),S,13,DENILSON,NaN,Y1',1,0
7264,238,1596,BUL,VYTLACIL Rudolf (TCH),S,11,Ivan KOLEV,NaN,Y1',1,0
...,...,...,...,...,...,...,...,...,...,...,...
36964,255951,300186503,ARG,SABELLA Alejandro (ARG),S,7,DI MARIA,NaN,G118' Y120',1,0
36972,255951,300186503,ARG,SABELLA Alejandro (ARG),S,16,ROJO,NaN,Y90' O105',1,0
36997,255951,300186503,SUI,HITZFELD Ottmar (GER),N,16,FERNANDES,NaN,I66' Y73',1,0
37006,255951,300186497,BEL,WILMOTS Marc (BEL),S,4,KOMPANY,C,Y42',1,0
37021,255951,300186497,USA,KLINSMANN Juergen (GER),S,20,CAMERON,NaN,Y18',1,0

In [ ]:
#Top  5 jugadores con mas amarillas
df_players_events.get(['Player Name','Team Initials','Yellow_Cards']).groupby(['Player Name','Team Initials'],as_index=False).sum().sort_values(by='Yellow_Cards',ascending=False).head(10)

         Player Name Team Initials  Yellow_Cards
555             CAFU           BRA             6
2413      MASCHERANO           ARG             5
3728  V. BRONCKHORST           NED             5
2513         MUNTARI           GHA             5
1472        HEITINGA           NED             4
2955     POPESCU GH.           ROU             4
2953            POPE           USA             4
4009   Zlatko YANKOV           BUL             4
1802     Jan WOUTERS           NED             4
556           CAHILL           AUS             4

Top 5 jugadores con mas rojas

In [ ]:
df_players_events.loc[(df_players_events['Player Name'].str.contains(pat='ZIDANE'))]

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Goals,Yellow_Cards,Red_Cards
13586,293,741,ALG,MEKHLOUFI Rachid (ALG),S,14,Djamel ZIDANE,NaN,O64',0,0,0
15869,308,379,ALG,SAADANE Rabah (ALG),S,14,Djamel ZIDANE,NaN,G59' O71',1,0,0
16326,308,377,ALG,SAADANE Rabah (ALG),N,14,Djamel ZIDANE,NaN,I80',0,0,0
17057,308,378,ALG,SAADANE Rabah (ALG),S,14,Djamel ZIDANE,NaN,O58',0,0,0
22736,1014,8730,FRA,JACQUET Aime (FRA),S,10,Zinedine ZIDANE,NaN,Y75',0,1,0
23392,1014,8745,FRA,JACQUET Aime (FRA),S,10,Zinedine ZIDANE,NaN,R71',0,0,1
25243,1027,8788,FRA,JACQUET Aime (FRA),S,10,Zinedine ZIDANE,NaN,G27' G45',2,0,0
28780,97410100,97410013,FRA,DOMENECH Raymond (FRA),S,10,ZIDANE,C,Y72',0,1,0
29517,97410100,97410029,FRA,DOMENECH Raymond (FRA),S,10,ZIDANE,C,Y85' O90',0,1,0
30760,97410200,97410056,FRA,DOMENECH Raymond (FRA),S,10,ZIDANE,C,Y90' G90',1,1,0
31036,97410400,97410062,FRA,DOMENECH Raymond (FRA),S,10,ZIDANE,C,P33',1,0,0
31128,97410600,97410064,FRA,DOMENECH Raymond (FRA),S,10,ZIDANE,C,P7' R110',1,0,1

In [ ]:
#Top  5 jugadores con mas rojas
df_players_events.get(['Player Name','Team Initials','Red_Cards']).groupby(['Player Name','Team Initials'],as_index=False).sum().sort_values(by='Red_Cards',ascending=False).head(5)

          Player Name Team Initials  Red_Cards
3413             SONG           CMR          2
3000     Pedro MONZON           ARG          1
3166  Rafael ALBRECHT           ARG          1
3140       RONALDINHO           BRA          1
457     Bassel GORGIS           IRQ          1

Top 5 mas goles entrando de suplentes

In [ ]:
players_goal_in = players.dropna(subset = ['Event'])

In [ ]:
players_goal_in = players_goal_in.loc[(players_goal_in['Event'].str.contains(pat='I')) & (players_goal_in['Event'].str.contains(pat='G'))]
#Falta la P de penales

NameError: ignored

In [ ]:
def cantidad_goles(cadena):
    return cadena.count('G') + cadena.count('P')

In [ ]:
players_goal_in['Goals'] = players_goal_in['Event'].apply(cantidad_goles)

In [ ]:
players_goal_in.get(['Player Name','Team Initials','Goals']).groupby(['Player Name','Team Initials'],as_index=False).sum().sort_values(by='Goals',ascending=False).head(5)

     Player Name Team Initials  Goals
127  Roger MILLA           CMR      5
21        CUEVAS           PAR      3
130     SCHÔøΩRRLE           GER      3
85   Laszlo KISS           HUN      3
24     DEL PIERO           ITA      2

Jugador con mas autogoles en mundiales

In [ ]:
def cantidad_autgoles(cadena):
    return cadena.count('W')

In [ ]:
auto_goal = players.dropna(subset = ['Event'])

In [ ]:
auto_goal = auto_goal.loc[(auto_goal['Event'].str.contains(pat='W'))]

In [ ]:
auto_goal['Auto_Goals'] = auto_goal['Event'].apply(cantidad_autgoles)

In [ ]:
#Todos solo con un autogol
auto_goal.get(['Player Name','Team Initials','Auto_Goals']).groupby(['Player Name','Team Initials'],as_index=False).sum().sort_values(by='Auto_Goals',ascending=False)

             Player Name Team Initials  Auto_Goals
0                  AGGER           DEN           1
21             KOLAÔøΩINAC           BIH           1
23             Luis CRUZ           URU           1
24               MARCELO           BRA           1
25          Manuel ROSAS           MEX           1
26                 PETIT           POR           1
27                 PUYOL           ESP           1
28           Pierre ISSA           RSA           1
29         Raul CARDENAS           MEX           1
30       Roberto PERFUMO           ARG           1
31             Ruud KROL           NED           1
32                SANCHO           TRI           1
33     Sinisa MIHAJLOVIC           YUG           1
34        Sven JACOBSSON           SWE           1
35              Tom BOYD           SCO           1
36            VALLADARES           HON           1
37                  YOBO           NGA           1
38        Youssef CHIPPO           MAR           1
39             ZACCARDO            ITA           1
22          Laszlo DAJKA           HUN           1
20          Jozef BARMOS           TCH           1
1                  AGOOS           USA           1
19            Jose PARRA           ESP           1
2   Andranik ESKANDARIAN           IRN           1
3         Andres ESCOBAR           COL           1
4                   BOYE           GHA           1
5            Berti VOGTS           FRG           1
6          CHO Kwang Rae           KOR           1
7               CHUYOUNG           KOR           1
8           Colin CURRAN           AUS           1
9          Ernie BRANDTS           NED           1
10      Ernst LOERTSCHER           SUI           1
11               GAMARRA           PAR           1
12         Georgi BACHEV           BUL           1
13          Ivan DAVIDOV           BUL           1
14           Ivan HORVAT           YUG           1
15           Ivan VUTSOV           BUL           1
16              J. COSTA           POR           1
17         Javier GUZMAN           MEX           1
18       Jimmy DICKINSON           ENG           1
40           ZUBIZARRETA           ESP           1

## 2.4 DF Matches World Cups - EDA

### 2.4.1 Check Values of Win  conditions

In [ ]:
matches_worldcups['Win conditions'].value_counts()
#Information about unique form to win the match

                                                 787
Italy win after extra time                         5
Germany win after extra time                       4
Argentina win after extra time                     4
Belgium win after extra time                       3
Win on Golden Goal                                 3
England win after extra time                       3
Brazil win on penalties (3 - 2)                    3
Netherlands win on penalties (4 - 3)               2
Argentina win on penalties (2 - 4)                 2
France win after extra time                        2
France win on penalties (3 - 4)                    2
Costa Rica win on penalties (5 - 3)                2
 win on penalties (5 - 4)                          1
Germany FR win on penalties (4 - 1)                1
Brazil win after extra time                        1
Czechoslovakia win after extra time                1
Hungary win after extra time                       1
Spain win after extra time                         1
Uruguay win on penalties (4 - 2)                   1
Paraguay win on penalties (5 - 3)                  1
Ghana win after extra time                         1
Italy win on penalties (5 - 3)                     1
Portugal win on penalties (1 - 3)                  1
Germany win on penalties (4 - 2)                   1
Ukraine win on penalties (0 - 3)                   1
Korea Republic win on penalties (3 - 5)            1
Northern Ireland win after extra time              1
Spain win on penalties (3 - 2)                     1
Brazil win on penalties (4 - 2)                    1
Argentina win on penalties (4 - 3)                 1
Germany FR win after extra time                    1
Sweden win on penalties (4 - 5)                    1
Bulgaria win on penalties (1 - 3)                  1
 win on penalties (4 - 3)                          1
Austria win after extra time                       1
 win on penalties (2 - 3)                          1
Yugoslavia win after extra time                    1
Republic of Ireland win on penalties (5 - 4)       1
Cameroon win after extra time                      1
Uruguay win after extra time                       1
Belgium win on penalties (4 - 5)                   1
 win on penalties (3 - 4)                          1
Name: Win conditions, dtype: int64

### 2.4.2 Drop NA

In [ ]:
matches_worldcups
#Hay muchos registros que todas las columnas son NA por ende primero vamos a eliminarlas
#Como notamos son despues de la final de 2014 quizas eran las filas para los mundiales restantes

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4570,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
matches_wc = matches_worldcups.dropna() #Borrar valores NA de la columna dropna

In [ ]:
print(f'Tama√±o df original {matches_worldcups.shape},Tama√±o del df sin na {matches_wc.shape}')

Tama√±o df original (4572, 20),Tama√±o del df sin na (850, 20)

### 2.4.3 Drop Duplicates

In [ ]:
matches_wc.loc[(matches_wc['Home Team Name'] == 'Brazil') & (matches_wc['Away Team Name'] == 'Germany')]
#Buscamos un partido especifico y como vemos existen valores duplicados
#Procedemos a eliminarlos para tener mas limpio nuestro data set

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
826,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,,58141.0,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955.0,300186474.0,BRA,GER
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,,58141.0,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955.0,300186474.0,BRA,GER

In [ ]:
matches_worldcup = matches_wc.drop_duplicates()

In [ ]:
matches_worldcup.shape

(835, 20)

In [ ]:
matches_worldcup.loc[(matches_worldcup['Home Team Name'] == 'Brazil') & (matches_worldcup['Away Team Name'] == 'Germany')]
#Comprobamos que ya no esta el partido de Brazil vs Germany duplicado

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
826,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,,58141.0,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955.0,300186474.0,BRA,GER

In [ ]:
print(f'Tama√±o df previo {matches_wc.shape},Tama√±o del df sin duplicados {matches_worldcup.shape}')

Tama√±o df previo (850, 20),Tama√±o del df sin duplicados (835, 20)

Verificamos que ya no existen nulos ni duplicados

In [ ]:
matches_worldcup.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 835 entries, 0 to 835
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  835 non-null    float64
 1   Datetime              835 non-null    object
 2   Stage                 835 non-null    object
 3   Stadium               835 non-null    object
 4   City                  835 non-null    object
 5   Home Team Name        835 non-null    object
 6   Home Team Goals       835 non-null    float64
 7   Away Team Goals       835 non-null    float64
 8   Away Team Name        835 non-null    object
 9   Win conditions        835 non-null    object
 10  Attendance            835 non-null    float64
 11  Half-time Home Goals  835 non-null    float64
 12  Half-time Away Goals  835 non-null    float64
 13  Referee               835 non-null    object
 14  Assistant 1           835 non-null    object
 15  Assistant 2           835 non-null    object
 16  RoundID               835 non-null    float64
 17  MatchID               835 non-null    float64
 18  Home Team Initials    835 non-null    object
 19  Away Team Initials    835 non-null    object
dtypes: float64(8), object(12)
memory usage: 137.0+ KB

### 2.4.4 Convertir tipos de datos en las columnas

In [ ]:
matches_worldcup.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

In [ ]:
#Convertir multiples columnas usando un diccionario
# using dictionary to convert specific columns
convert_dict = {
                'Year': int,
                'Home Team Goals': int,
                'Away Team Goals': int,
                'Attendance':int,
                'Half-time Home Goals':int,
                'Half-time Away Goals':int,
                'RoundID':int,
                'MatchID':int
                }


matches_worldcup = matches_worldcup.astype(convert_dict)

In [ ]:
matches_worldcup.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

In [ ]:
#Convertir columna de datetime
#Formatear cada registro de datetime cuando se adecuado formato
# Create a mapping of date formats and their corresponding format strings
format_mapping = {
    r'%d %b %Y - %H:%M ': 0,
    r'%d %B %Y - %H:%M ': 1,
    r'%d %b %Y %H:%M': 2,
    r'%Y-%m-%d %H:%M': 3,
    r'%B %d, %Y %I:%M %p': 4
}

# Preprocess the data
def preprocess_datetime(datetime_str):
    for format_str, format_id in format_mapping.items():
        try:
            return pd.to_datetime(datetime_str, format=format_str)
        except ValueError:
            continue
    return pd.NaT

# Convert the "Datetime" column using the preprocess function
matches_worldcup['Datetime'] = matches_worldcup['Datetime'].apply(preprocess_datetime)

In [ ]:
matches_worldcup.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

### 2.4.5 Encontrar insights
- Top 10 Arbitros con mas partidos
- Partido con Mas Goles
- Mas goles realizados por un local
- Mas goles realizados por un visitante
- Partido con mas asistencia
- Ronda de grupo con mas goles x a√±o
- Final con mas goles
- Final decidida por penales

In [ ]:
matches_worldcup['Stage'].unique()

array(['Group 1', 'Group 4', 'Group 2', 'Group 3', 'Semi-finals', 'Final',
       'Preliminary round', 'Quarter-finals', 'Match for third place',
       'First round', 'Group 6', 'Group B', 'Group A', 'Group 5',
       'Group C', 'Group D', 'Group F', 'Group E', 'Round of 16',
       'Group H', 'Group G', 'Third place', 'Play-off for third place'],
      dtype=object)

In [ ]:
referee_counts = matches_worldcup['Referee'].value_counts()
assistant1_counts = matches_worldcup['Assistant 1'].value_counts()
assistant2_counts = matches_worldcup['Assistant 2'].value_counts()

In [ ]:
combined_counts = pd.concat([referee_counts, assistant1_counts, assistant2_counts], axis=1, sort=True)
combined_counts.columns = ['Referee', 'Assistant 1', 'Assistant 2']

In [ ]:
combined_counts

                          Referee  Assistant 1  Assistant 2
ABD EL FATAH Essam (EGY)      1.0          NaN          NaN
ABDUL HAMID Halim (MAS)       NaN          2.0          2.0
ACHIK Redouane (MAR)          NaN          5.0          NaN
ACKEBORN Gosta (SWE)          NaN          NaN          1.0
ADAIR John (NIR)              1.0          2.0          NaN
...                           ...          ...          ...
ZARATE Venancio (PAR)         NaN          4.0          2.0
ZECEVIC Konstantin (YUG)      1.0          NaN          2.0
ZENISEK Bohumil (TCH)         NaN          1.0          3.0
ZSOLT Istvan (HUN)            5.0          4.0          3.0
ZUMBA Juan (SLV)              NaN          NaN          2.0

[659 rows x 3 columns]

In [ ]:
combined_counts = combined_counts.fillna(0)

In [ ]:
combined_counts['Total Appearances'] = combined_counts['Referee'] + combined_counts['Assistant 1'] + combined_counts['Assistant 2']

In [ ]:
combined_counts = combined_counts.reset_index().rename(columns={'index': 'Person'}).sort_values(by='Total Appearances', ascending=False).reset_index(drop=True)

In [ ]:
combined_counts.head(10)

,Person,Referee,Assistant 1,Assistant 2,Total Appearances
0,VERGARA Hector (CAN),0.0,7.0,7.0,14.0
1,GARDEAZABAL Juan (ESP),7.0,2.0,4.0,13.0
2,ELLIS Arthur (ENG),6.0,5.0,2.0,13.0
3,RAINEA Nicolae (ROU),5.0,4.0,4.0,13.0
4,AL SHARIF Jamal (SYR),6.0,1.0,5.0,12.0
5,GRIFFITHS Benjamin (WAL),7.0,3.0,2.0,12.0
6,ZSOLT Istvan (HUN),5.0,4.0,3.0,12.0
7,DAVIDSON Bob (SCO),4.0,4.0,4.0,12.0
8,PALOTAI Karoly (HUN),4.0,4.0,4.0,12.0
9,QUINIOU Joel (FRA),8.0,3.0,1.0,12.0

Top 10 referees apariciones

In [ ]:
referee = matches_worldcup['Referee'].value_counts()
referee = referee.reset_index()
referee.columns = ['Referee', 'Appearances']
referee.head(10)

                    Referee  Appearances
0     Ravshan IRMATOV (UZB)            9
1     LARRIONDA Jorge (URU)            8
2        QUINIOU Joel (FRA)            8
3    ARCHUNDIA Benito (MEX)            8
4  DE BLEECKERE Frank (BEL)            7
5         BUJSAIM Ali (UAE)            7
6     RODRIGUEZ Marco (MEX)            7
7  GRIFFITHS Benjamin (WAL)            7
8       LANGENUS Jean (BEL)            7
9        SIMON Carlos (BRA)            7

Top 10 Assistant 1 apariciones

In [ ]:
assistant1 = matches_worldcup['Assistant 1'].value_counts()
assistant1  = assistant1 .reset_index()
assistant1 .columns = ['Assistant 1', 'Appearances']
assistant1 .head(10)

                        Assistant 1  Appearances
0  GONZALEZ ARCHUNDIA Alfonso (MEX)            7
1               HERMANS Peter (BEL)            7
2              VERGARA Hector (CAN)            7
3               BERANEK Alois (AUT)            7
4            FREDRIKSSON Erik (SWE)            6
5                SHARP Philip (ENG)            6
6                DUSCH Albert (GER)            5
7                GARCIA Dario (ARG)            5
8    FERNANDES CAMPOS Joaquim (POR)            5
9                RAMIREZ Jose (MEX)            5

Top 10 Assistant 2 apariciones

In [ ]:
assistant2 = matches_worldcup['Assistant 2'].value_counts()
assistant2  = assistant2.reset_index()
assistant2 .columns = ['Assistant 2', 'Appearances']
assistant2 .head(10)

                Assistant 2  Appearances
0  KOCHKAROV Bakhadyr (KGZ)            9
1      VERGARA Hector (CAN)            7
2      VROMANS Walter (BEL)            7
3  LISTKIEWICZ Michal (POL)            7
4          YUSTE Juan (ESP)            6
5       DANTE Dramane (MLI)            6
6         AMLER Evzen (CZE)            6
7         SNODDY Alan (NIR)            5
8  ULLOA MORERA Berny (CRC)            5
9      COELHO Arnaldo (BRA)            5



```
# Tiene formato de c√≥digo
```

10 partidos con mas goles

In [ ]:
matches_worldcup['Total_Goals'] = matches_worldcup['Home Team Goals'] + matches_worldcup['Away Team Goals']

In [ ]:
matches_worldcup.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials',
       'Total_Goals'],
      dtype='object')

In [ ]:
matches_worldcup.get(['Year','Stage','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name','Total_Goals']).sort_values(by='Total_Goals',ascending=False).reset_index(drop=True).head(10)

,Year,Stage,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Total_Goals
0,1954,Quarter-finals,Austria,7,5,Switzerland,12
1,1938,First round,Brazil,6,5,Poland,11
2,1954,Group 2,Hungary,8,3,Germany FR,11
3,1982,Group 3,Hungary,10,1,El Salvador,11
4,1958,Group 2,France,7,3,Paraguay,10
5,1954,Group 2,Germany FR,7,2,Turkey,9
6,1974,Group 2,Yugoslavia,9,0,Zaire,9
7,1930,Group 1,Argentina,6,3,Mexico,9
8,1958,Match for third place,France,6,3,Germany FR,9
9,1954,Group 2,Hungary,9,0,Korea Republic,9

Top 10 goleadas historicas de locales

In [ ]:
matches_worldcup.get(['Year','Stage','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name']).sort_values(by='Home Team Goals',ascending=False).reset_index(drop=True).head(10)

,Year,Stage,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name
0,1982,Group 3,Hungary,10,1,El Salvador
1,1974,Group 2,Yugoslavia,9,0,Zaire
2,1954,Group 2,Hungary,9,0,Korea Republic
3,1950,Group 4,Uruguay,8,0,Bolivia
4,1954,Group 2,Hungary,8,3,Germany FR
5,1938,Quarter-finals,Sweden,8,0,Cuba
6,2002,Group E,Germany,8,0,Saudi Arabia
7,2010,Group G,Portugal,7,0,Korea DPR
8,1934,Preliminary round,Italy,7,1,USA
9,1958,Group 2,France,7,3,Paraguay

Top 10 goleadas historicas de visitantes

In [ ]:
matches_worldcup.get(['Year','Stage','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name']).sort_values(by='Away Team Goals',ascending=False).reset_index(drop=True).head(10)

,Year,Stage,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name
0,2014,Semi-finals,Brazil,1,7,Germany
1,1974,Group 4,Haiti,0,7,Poland
2,2014,Group E,Switzerland,2,5,France
3,1954,Quarter-finals,Austria,7,5,Switzerland
4,1990,Group A,USA,1,5,Czechoslovakia
5,2014,Group B,Spain,1,5,Netherlands
6,1938,First round,Brazil,6,5,Poland
7,2002,Group C,Costa Rica,2,5,Brazil
8,1986,Round of 16,Denmark,1,5,Spain
9,1990,Group B,Cameroon,0,4,Soviet Union

Remontada de visitantes despues de ir perdiendo finalizado el primer tiempo

In [ ]:
matches_worldcup.loc[(matches_worldcup['Half-time Home Goals'] > matches_worldcup['Half-time Away Goals']) & (matches_worldcup['Away Team Goals'] > matches_worldcup['Home Team Goals'])]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Total_Goals
443,1990,1990-06-20 21:00:00,Group C,Luigi Ferraris,Genoa,Sweden,1,2,Costa Rica,,...,1,0,PETROVIC Zoran (SRB),SNODDY Alan (NIR),COURTNEY George (ENG),322,128,SWE,CRC,3
524,1998,1998-06-13 17:30:00,Group E,Stade de Gerland,Lyon,Korea Republic,1,3,Mexico,,...,1,0,BENKO Gunter (AUT),FRED Lencie (VAN),SCHNEIDER Erich (GER),1014,8732,KOR,MEX,4
618,2002,2002-06-12 20:30:00,Group B,Jeju World Cup Stadium,Jeju,Slovenia,1,3,Paraguay,,...,1,0,RAMOS RIZO Felipe (MEX),LINDBERG Leif (SWE),KRISHNAN Visva (SIN),43950100,43950040,SVN,PAR,4
777,2014,2014-06-14 16:00:00,Group D,Estadio Castelao,Fortaleza,Uruguay,1,3,Costa Rica,,...,1,0,BRYCH Felix (GER),BORSCH Mark (GER),LUPP Stefan (GER),255931,300186489,URU,CRC,4

Remontada de locales  despues de ir perdiendo finalizado el primer tiempo

In [ ]:
matches_worldcup.loc[(matches_worldcup['Half-time Home Goals'] < matches_worldcup['Half-time Away Goals']) & (matches_worldcup['Away Team Goals'] < matches_worldcup['Home Team Goals'])].head(10)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Total_Goals
17,1930,1930-07-30 14:15:00,Final,Estadio Centenario,Montevideo,Uruguay,4,2,Argentina,,...,1,2,LANGENUS Jean (BEL),SAUCEDO Ulises (BOL),CRISTOPHE Henry (BEL),405,1087,URU,ARG,6
22,1934,1934-05-27 16:30:00,Preliminary round,Giovanni Berta,Florence,Germany,5,2,Belgium,,...,1,2,MATTEA Francesco (ITA),MELANDRI Ermenegildo (ITA),BAERT Jacques (FRA),204,1108,GER,BEL,7
25,1934,1934-05-27 16:30:00,Preliminary round,Littorio,Trieste,Czechoslovakia,2,1,Romania,,...,0,1,LANGENUS Jean (BEL),SCARPI Giuseppe (ITA),SCORZONI Raffaele (ITA),204,1141,TCH,ROU,3
42,1938,1938-06-09 18:00:00,First round,Stade Municipal,Toulouse,Cuba,2,1,Romania,,...,0,1,BIRLEM Alfred (GER),CAPDEVILLE Pierre (FRA),MARENCO Paul (FRA),206,1157,CUB,ROU,3
43,1938,1938-06-09 18:00:00,First round,Parc des Princes,Paris,Switzerland,4,2,Germany,,...,1,2,EKLIND Ivan (SWE),BAERT Louis (BEL),VAN MOORSEL Johannes (NED),206,1166,SUI,GER,6
48,1938,1938-06-14 18:00:00,Quarter-finals,Stade du Parc Lescure,Bordeaux,Brazil,2,1,Czechoslovakia,,...,0,1,CAPDEVILLE Georges (FRA),MARENCO Paul (FRA),KISSENBERGER Ernest (FRA),429,1153,BRA,TCH,3
51,1938,1938-06-19 17:00:00,Match for third place,Stade du Parc Lescure,Bordeaux,Brazil,4,2,Sweden,,...,1,2,LANGENUS Jean (BEL),OLIVE D. (FRA),VALPREDE Ferdinand (FRA),3488,1151,BRA,SWE,6
55,1950,1950-06-25 15:00:00,Group 2,Durival de Brito,Curitiba,Spain,3,1,USA,,...,0,1,VIANA Mario (BRA),DA COSTA VIEIRA Jose (POR),DE LA SALLE Charles (FRA),208,1208,ESP,USA,4
72,1950,1950-07-13 15:00:00,Group 6,Pacaembu,Sao Paulo,Uruguay,3,2,Sweden,,...,1,2,GALEATI Giovanni (ITA),BERANEK Alois (AUT),DE NICOLA Cayetano (PAR),209,1231,URU,SWE,5
127,1958,1958-06-17 19:00:00,Group 3,Rasunda Stadium,Solna,Wales,2,1,Hungary,,...,0,1,LATYCHEV Nikolaj (URS),CODESAL Jose Maria (URU),ERIKSSON Arne (FIN),220,1408,WAL,HUN,3

Top 10 partidos con mas asistencias

In [ ]:
matches_worldcup.get(['Datetime','Stage','Stadium','City','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name','Attendance']).sort_values(by='Attendance',ascending=False).reset_index(drop=True).head(10)

,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Attendance
0,1950-07-16 15:00:00,Group 6,MaracanÔøΩ - EstÔøΩdio Jornalista MÔøΩrio Filho,Rio De Janeiro,Uruguay,2,1,Brazil,173850
1,1950-07-13 15:00:00,Group 6,MaracanÔøΩ - EstÔøΩdio Jornalista MÔøΩrio Filho,Rio De Janeiro,Brazil,6,1,Spain,152772
2,1950-07-01 15:00:00,Group 1,MaracanÔøΩ - EstÔøΩdio Jornalista MÔøΩrio Filho,Rio De Janeiro,Brazil,2,0,Yugoslavia,142429
3,1950-07-09 15:00:00,Group 6,MaracanÔøΩ - EstÔøΩdio Jornalista MÔøΩrio Filho,Rio De Janeiro,Brazil,7,1,Sweden,138886
4,1986-06-29 12:00:00,Final,Estadio Azteca,Mexico City,Argentina,3,2,Germany FR,114600
5,1986-06-07 12:00:00,Group B,Estadio Azteca,Mexico City,Mexico,1,1,Paraguay,114600
6,1986-06-15 12:00:00,Round of 16,Estadio Azteca,Mexico City,Mexico,2,0,Bulgaria,114580
7,1986-06-22 12:00:00,Quarter-finals,Estadio Azteca,Mexico City,Argentina,2,1,England,114580
8,1986-06-25 16:00:00,Semi-finals,Estadio Azteca,Mexico City,Argentina,2,0,Belgium,114500
9,1986-06-03 12:00:00,Group B,Estadio Azteca,Mexico City,Belgium,1,2,Mexico,110000

Top 10 grupo con mas goles por a√±o

In [ ]:
matches_worldcup['Stage'].unique()

array(['Group 1', 'Group 4', 'Group 2', 'Group 3', 'Semi-finals', 'Final',
       'Preliminary round', 'Quarter-finals', 'Match for third place',
       'First round', 'Group 6', 'Group B', 'Group A', 'Group 5',
       'Group C', 'Group D', 'Group F', 'Group E', 'Round of 16',
       'Group H', 'Group G', 'Third place', 'Play-off for third place'],
      dtype=object)

In [ ]:
groups_matcheswc = matches_worldcup.loc[(matches_worldcup['Stage'].isin(['Group 1', 'Group 4', 'Group 2', 'Group 3','Group 5','Group 6','Group B', 'Group A',
                                                      'Group C', 'Group D', 'Group F', 'Group E','Group H', 'Group G']))]

In [ ]:
groups_matcheswc.get(['Year','Stage','Total_Goals']).groupby(['Year','Stage'],as_index=False).sum().sort_values(by='Total_Goals',ascending=False).head(10)

    Year    Stage  Total_Goals
10  1954  Group 2           41
43  1982  Group 3           34
8   1950  Group 6           31
14  1958  Group 2           31
13  1958  Group 1           27
46  1982  Group 6           26
44  1982  Group 4           26
32  1974  Group 4           26
17  1962  Group 1           25
28  1970  Group 4           24

In [ ]:
groups_matcheswc.loc[(groups_matcheswc['Year'] == 1982) & (groups_matcheswc['Stage'] == 'Group 4')]

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,...,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials,Total_Goals
315,1982,1982-06-16 17:15:00,Group 4,San Mames,Bilbao,England,3,1,France,,...,1,1,GARRIDO Antonio (POR),CASTRO Gaston (CHI),COELHO Arnaldo (BRA),293,878,ENG,FRA,4
318,1982,1982-06-17 17:45:00,Group 4,Jose Zorrilla,Valladolid,Czechoslovakia,1,1,Kuwait,,...,1,0,DWOMOH Benjamin (GHA),MENDEZ MOLINA Romulo (GUA),VALENTINE Robert (SCO),293,1012,TCH,KUW,2
327,1982,1982-06-20 17:15:00,Group 4,San Mames,Bilbao,England,2,0,Czechoslovakia,,...,0,0,CORVER Charles (NED),DOTCHEV Bogdan (BUL),ARISTIZABAL MURCIA Gilberto (COL),293,889,ENG,TCH,2
330,1982,1982-06-21 17:15:00,Group 4,Jose Zorrilla,Valladolid,France,4,1,Kuwait,,...,2,0,STUPAR Miroslav (URS),FREDRIKSSON Erik (SWE),MATOVINOVIC Damir (CRO),293,919,FRA,KUW,5
339,1982,1982-06-24 17:15:00,Group 4,Jose Zorrilla,Valladolid,France,1,1,Czechoslovakia,,...,0,0,CASARIN Paolo (ITA),DWOMOH Benjamin (GHA),PALOTAI Karoly (HUN),293,922,FRA,TCH,2
342,1982,1982-06-25 17:15:00,Group 4,San Mames,Bilbao,England,1,0,Kuwait,,...,1,0,ARISTIZABAL MURCIA Gilberto (COL),LUND-SORENSEN Henning (DEN),GARCIA CARRION Jose L. (ESP),293,882,ENG,KUW,1
344,1982,1982-06-28 17:15:00,Group 4,Vicente Calderon,Madrid,Austria,0,1,France,,...,0,1,PALOTAI Karoly (HUN),CHRISTOV Vojtech (TCH),MATOVINOVIC Damir (CRO),294,767,AUT,FRA,1
348,1982,1982-07-01 17:15:00,Group 4,Vicente Calderon,Madrid,Austria,2,2,Northern Ireland,,...,0,1,PROKOP Adolf (GDR),FREDRIKSSON Erik (SWE),ESCHWEILER Walter (GER),294,771,AUT,NIR,4
352,1982,1982-07-04 17:15:00,Group 4,Vicente Calderon,Madrid,France,4,1,Northern Ireland,,...,1,0,JARGUZ Alojzy (POL),RAINEA Nicolae (ROU),EL GHOUL Yusef Mohamed (LBY),294,920,FRA,NIR,5

Top 10 finales con mas asistentes

In [ ]:
matches_worldcup.get(['Datetime','Stage','Stadium','City','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name','Win conditions','Attendance','Total_Goals'])\
.loc[(matches_worldcup['Stage'] == 'Final')]\
.sort_values(by='Attendance',ascending=False).reset_index(drop=True).head(10)

,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Total_Goals
0,1986-06-29 12:00:00,Final,Estadio Azteca,Mexico City,Argentina,3,2,Germany FR,,114600,5
1,1970-06-21 12:00:00,Final,Estadio Azteca,Mexico City,Brazil,4,1,Italy,,107412,5
2,1966-07-30 15:00:00,Final,Wembley Stadium,London,England,4,2,Germany FR,England win after extra time,96924,6
3,1994-07-17 12:30:00,Final,Rose Bowl,Los Angeles,Brazil,0,0,Italy,Brazil win on penalties (3 - 2),94194,0
4,1982-07-11 20:00:00,Final,Santiago Bernabeu,Madrid,Italy,3,1,Germany FR,,90000,4
5,2010-07-11 20:30:00,Final,Soccer City Stadium,Johannesburg,Netherlands,0,1,Spain,Spain win after extra time,84490,1
6,1998-07-12 21:00:00,Final,Stade de France,Saint-Denis,Brazil,0,3,France,,80000,3
7,1974-07-07 16:00:00,Final,Olympiastadion,Munich,Netherlands,1,2,Germany FR,,78200,3
8,2014-07-13 16:00:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,Germany win after extra time,74738,1
9,1990-07-08 20:00:00,Final,Stadio Olimpico,Rome,Germany FR,1,0,Argentina,,73603,1

Top 10 finales con mas goles

In [ ]:
matches_worldcup.get(['Datetime','Stage','Stadium','City','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name','Win conditions','Attendance','Total_Goals'])\
.loc[(matches_worldcup['Stage'] == 'Final')]\
.sort_values(by='Total_Goals',ascending=False).reset_index(drop=True).head(10)

,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Total_Goals
0,1958-06-29 15:00:00,Final,Rasunda Stadium,Solna,Brazil,5,2,Sweden,,49737,7
1,1930-07-30 14:15:00,Final,Estadio Centenario,Montevideo,Uruguay,4,2,Argentina,,68346,6
2,1938-06-19 17:00:00,Final,Stade Olympique,Colombes,Italy,4,2,Hungary,,45000,6
3,1966-07-30 15:00:00,Final,Wembley Stadium,London,England,4,2,Germany FR,England win after extra time,96924,6
4,1954-07-04 17:00:00,Final,Wankdorf Stadium,Berne,Germany FR,3,2,Hungary,,62500,5
5,1986-06-29 12:00:00,Final,Estadio Azteca,Mexico City,Argentina,3,2,Germany FR,,114600,5
6,1970-06-21 12:00:00,Final,Estadio Azteca,Mexico City,Brazil,4,1,Italy,,107412,5
7,1982-07-11 20:00:00,Final,Santiago Bernabeu,Madrid,Italy,3,1,Germany FR,,90000,4
8,1978-06-25 15:00:00,Final,El Monumental - Estadio Monumental Antonio Ves...,Buenos Aires,Argentina,3,1,Netherlands,Argentina win after extra time,71483,4
9,1962-06-17 14:30:00,Final,Nacional,Santiago De Chile,Brazil,3,1,Czechoslovakia,,68679,4

Finales ganadas en penalties

In [ ]:
matches_worldcup.get(['Datetime','Stage','Stadium','City','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name','Win conditions','Attendance','Total_Goals'])\
.loc[(matches_worldcup['Stage'] == 'Final') & (matches_worldcup['Win conditions'].str.contains(pat='penalties'))]

,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Total_Goals
515,1994-07-17 12:30:00,Final,Rose Bowl,Los Angeles,Brazil,0,0,Italy,Brazil win on penalties (3 - 2),94194,0
707,2006-07-09 20:00:00,Final,Olympiastadion,Berlin,Italy,1,1,France,Italy win on penalties (5 - 3),69000,2

## 2.5  Merge DF Matches Players and WorlCups
Encontrar insights
- Partido con mas amarillas
- Partido con mas rojas
- Mundial con mas autogoles

In [ ]:
df_players_events

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Goals,Yellow_Cards,Red_Cards
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40',1,0,0
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70',1,0,0
6,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Andre MASCHINOT,NaN,G43' G87',2,0,0
14,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Lucien LAURENT,NaN,G19',1,0,0
35,201,1090,USA,MILLAR Bob (USA),S,0,Tom FLORIE,C,G45',1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
37030,255951,300186497,BEL,WILMOTS Marc (BEL),N,9,LUKAKU,NaN,I91' G105',1,0,0
37032,255951,300186497,BEL,WILMOTS Marc (BEL),N,11,MIRALLAS,NaN,I60',0,0,0
37040,255951,300186497,BEL,WILMOTS Marc (BEL),N,22,CHADLI,NaN,I111',0,0,0
37041,255951,300186497,USA,KLINSMANN Juergen (GER),N,16,GREEN,NaN,I105' G107',1,0,0
37045,255951,300186497,USA,KLINSMANN Juergen (GER),N,18,WONDOLOWSKI,NaN,I72',0,0,0

Partido con mas amarillas

In [ ]:
most_yellows_cards = df_players_events.get(['MatchID','Yellow_Cards']).groupby(['MatchID'],as_index=False).sum().sort_values(by='Yellow_Cards',ascending=False)

In [ ]:
pd.merge(most_yellows_cards,matches_worldcup. \
         get(['Datetime','Stage','Stadium','City','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name','MatchID']),on ='MatchID').head(2)

,MatchID,Yellow_Cards,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name
0,43950035,16,2002-06-11 20:30:00,Group E,Shizuoka Stadium Ecopa,Shizuoka,Cameroon,0,2,Germany
1,97410052,16,2006-06-25 21:00:00,Round of 16,Franken-Stadion,Nuremberg,Portugal,1,0,Netherlands

In [ ]:
most_reds_cards = df_players_events.get(['MatchID','Red_Cards']).groupby(['MatchID'],as_index=False).sum().sort_values(by='Red_Cards',ascending=False)

Partido con mas rojas

In [ ]:
pd.merge(most_reds_cards,matches_worldcup. \
         get(['Datetime','Stage','Stadium','City','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name','MatchID']),on ='MatchID').head(1)

,MatchID,Red_Cards,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name
0,97410052,4,2006-06-25 21:00:00,Round of 16,Franken-Stadion,Nuremberg,Portugal,1,0,Netherlands

Mundial con mas autogoles

In [ ]:
matches_world = matches_worldcup.get(['Year','MatchID'])

In [ ]:
matches_world.head()

   Year  MatchID
0  1930     1096
1  1930     1090
2  1930     1093
3  1930     1098
4  1930     1085

In [ ]:
auto_goal.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Auto_Goals
189,201,1095,MEX,LUQUE Juan (MEX),S,0,Manuel ROSAS,NaN,W51',1
1732,206,1166,SUI,RAPPAN Karl (AUT),S,0,Ernst LOERTSCHER,NaN,W22',1
1982,3489,1176,SWE,NAGY Joszef (HUN),S,0,Sven JACOBSSON,NaN,W19',1
2918,209,1186,ESP,EIZAGUIRRE Guillermo (ESP),S,0,Jose PARRA,NaN,W15',1
3341,211,1240,ENG,WINTERBOTTOM Walter (ENG),S,6,Jimmy DICKINSON,NaN,W94',1

In [ ]:
auto_goals_year = pd.merge(matches_world,auto_goal.get(['MatchID','Auto_Goals']),how='inner',on='MatchID')

In [ ]:
auto_goal_wc = auto_goals_year.get(['Year','Auto_Goals']).groupby(['Year'],as_index=False).sum()

Mundiales con sus respectivos autogoles

In [ ]:
pd.merge(worldcups.get(['Year','Country']),auto_goal_wc,how='inner',on='Year').sort_values(by='Auto_Goals',ascending=False).reset_index(drop=True)

    Year       Country  Auto_Goals
0   1998        France           6
1   2014        Brazil           5
2   1954   Switzerland           4
3   2006       Germany           4
4   1974       Germany           3
5   1978     Argentina           3
6   2002   Korea/Japan           3
7   1938        France           2
8   1966       England           2
9   1986        Mexico           2
10  2010  South Africa           2
11  1930       Uruguay           1
12  1950        Brazil           1
13  1970        Mexico           1
14  1982         Spain           1
15  1994           USA           1